name: Wellness Tourism Package Customer Prediction MLS pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r wellness_tourism_package_customer_prediction/requirements.txt

      - name: Upload Dataset to Hugging Face Hub
        run: |
          python wellness_tourism_package_customer_prediction/model_building/data_register.py

  data_prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r wellness_tourism_package_customer_prediction/requirements.txt

      - name: Run Data Preparation
        run: |
          python wellness_tourism_package_customer_prediction/model_building/data_prep.py

  model_training:
     needs: data_prep
     runs-on: ubuntu-latest
     env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      MLFLOW_TRACKING_URI: http://127.0.0.1:5000
      MLFLOW_EXPERIMENT_NAME: wellness_tourism_package_customer_prediction_experiments

     steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r wellness_tourism_package_customer_prediction/requirements.txt
          pip install mlflow

      - name: Start MLflow Server
        run: |
          nohup mlflow server \
            --host 127.0.0.1 \
            --port 5000 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root ./mlruns \
            > mlflow.log 2>&1 &
          sleep 5

      - name: Train Model (logs to MLflow)
        run: |
          python wellness_tourism_package_customer_prediction/model_building/train.py

      - name: Upload MLflow Logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: |
            mlruns
            mlflow.db
            mlflow.log


  deploy_hosting:
    needs: model_training
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r wellness_tourism_package_customer_prediction/requirements.txt

      - name: Push Hosting App
        run: |
          python wellness_tourism_package_customer_prediction/hosting/hosting.py



