name: Wellness Tourism Package Customer Prediction pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r wellness_tourism_package_customer_prediction/requirements.txt

      - name: Upload Dataset to Hugging Face Hub
        run: |
          python wellness_tourism_package_customer_prediction/model_building/data_register.py

  data_prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r wellness_tourism_package_customer_prediction/requirements.txt

      - name: Run Data Preparation
        run: |
          python wellness_tourism_package_customer_prediction/model_building/data_prep.py
  
  model_training:
   needs: data_prep
   runs-on: ubuntu-latest
   env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
    MLFLOW_TRACKING_URI: https://visaged-incongruent-verona.ngrok-free.dev
   steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r wellness_tourism_package_customer_prediction/requirements.txt
    - name: Verify MLflow server reachable
      run: |
        python - <<'PY'
        import os, requests
        uri = os.environ["MLFLOW_TRACKING_URI"].rstrip("/")
        r = requests.get(uri + "/api/2.0/mlflow/experiments/list", timeout=20)
        print("Status:", r.status_code)
        print(r.text[:300])
        PY
    - name: Train Model
      run: |
        python wellness_tourism_package_customer_prediction/model_building/train.py

  deploy_hosting:
    needs: model_training
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r wellness_tourism_package_customer_prediction/requirements.txt

      - name: Push Hosting App
        run: |
          python wellness_tourism_package_customer_prediction/hosting/hosting.py


